name: Install Git on Multiple OS

on: [push, pull_request]

jobs:
  install_git:
    runs-on: ${{ matrix.os }}
    
    # Define a matrix strategy for multiple operating systems and versions
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Set up environment
        run: echo "Setting up on ${{ matrix.os }}"

      # Step to install Git on Ubuntu
      - name: Install Git on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      # Step to install Git on Windows
      - name: Install Git on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install git -y

      # Step to install Git on macOS
      - name: Install Git on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install git

      - name: Verify Git installation
        run: git --version
